import { useState } from 'react';
import { Document, Page, StyleSheet, Text, View, pdf } from '@react-pdf/renderer';
import { Download } from 'lucide-react';
import { Button } from '../ui/Button';
import type { SummaryResponse } from '../../types/contracts';

const styles = StyleSheet.create({
  page: { paddingTop: 48, paddingBottom: 48, paddingHorizontal: 56, fontFamily: 'Helvetica', color: '#1a1a1a' },
  brand: { fontSize: 12, color: '#1d9e75', fontFamily: 'Helvetica-Bold', letterSpacing: 1 },
  title: { fontSize: 22, fontFamily: 'Helvetica-Bold', marginTop: 16, color: '#0f6e56' },
  subtitle: { fontSize: 11, color: '#666660', marginTop: 4 },
  divider: { marginTop: 18, marginBottom: 18, height: 1, backgroundColor: '#e6e6e3' },
  sectionLabel: { fontSize: 9, fontFamily: 'Helvetica-Bold', letterSpacing: 1, color: '#aaa9a3' },
  sectionBody: { fontSize: 11, lineHeight: 1.5, marginTop: 6, marginBottom: 14 },
  disclaimer: { position: 'absolute', bottom: 32, left: 56, right: 56, fontSize: 8, color: '#aaa9a3', lineHeight: 1.4 },
  footer: { position: 'absolute', bottom: 16, left: 56, right: 56, fontSize: 8, color: '#aaa9a3', textAlign: 'center' },
});

function SummaryPdfDocument({ summary }: { summary: SummaryResponse }) {
  const sections = summary.sections.slice().sort((a, b) => a.order - b.order);
  return (
    <Document title={summary.title} author="PreDoc">
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.brand}>PREDOC · VISIT SUMMARY</Text>
        <Text style={styles.title}>{summary.title}</Text>
        {summary.subtitle && <Text style={styles.subtitle}>{summary.subtitle}</Text>}
        <View style={styles.divider} />
        {sections.map((s) => (
          <View key={s.key} wrap={false}>
            <Text style={styles.sectionLabel}>{s.title.toUpperCase()}</Text>
            <Text style={styles.sectionBody}>{s.body}</Text>
          </View>
        ))}
        {summary.disclaimer && <Text style={styles.disclaimer}>{summary.disclaimer}</Text>}
        <Text style={styles.footer} fixed>
          Generated by PreDoc · {new Date(summary.generatedAt).toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

interface PdfExportProps {
  summary: SummaryResponse;
  label?: string;
}

export function PdfExport({ summary, label = 'Save as PDF' }: PdfExportProps) {
  const [generating, setGenerating] = useState(false);

  async function handleDownload() {
    setGenerating(true);
    try {
      const blob = await pdf(<SummaryPdfDocument summary={summary} />).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `predoc-${summary.sessionId.slice(0, 8)}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } finally {
      setGenerating(false);
    }
  }

  return (
    <Button
      label={label}
      variant="secondary"
      leadingIcon={<Download className="h-4 w-4" aria-hidden />}
      loading={generating}
      onClick={handleDownload}
      fullWidth
    />
  );
}
